name: Kelly Anne Pipe
description: Web Design and Development

url: https://kellyanne.dev
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

gems: [jekyll-paginate]
paginate: 5

markdown: kramdown
kramdown: 
  syntax_highlighter_opts:
    disable: true

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: kellygrape
   twitter: kellygrape
   facebook: kellygrape
   email: kellyanne.pipe@gmail.com

exclude: ["node_modules", "gulpfile.js", "package.json"]



defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: [ "writing" ]
      permalink: /writing/:title.html
  -
    scope:
      path: "works"
      type: "posts"
    values:
      categories: [ "works" ]
      permalink: /works/:title.html